### PR TITLE
Added support for PushButton (Eco-Button)

### PR DESCRIPTION
**Pull request by w3stbam**
As the title says, this adds support for the MAX push button, also called "ECO Taster".
Its mainly a copy of the Shutter Contact, just a minor adjustment was needed to get the right bit:

`isOpen : rawBitData.get(0)`

### CODE REVIEW

**Comment by fbeek** [comment]
Hey,

thank you for your help.
I will check the code and merge it until the weekend.

Regards 

fbeek

**Review by fbeek — APPROVED** [review]
Code looks good

**Comment by fbeek** [comment]
Can you send me a debug log of received on/off messages from the eco button for my documentation ?

**Comment by w3stbam** [comment]
Here comes the debug log, first block is on, second one is off:

19:40:39.398 [pimatic-maxcul] debug: incoming raw data from CUL: Z0BA2000212345603F93A000000
19:40:39.414 [pimatic-maxcul] debug: decoding Message Z0BA2000212345603F93A000000
19:40:39.419 [pimatic-maxcul] debug: RSSI for Message : -74
19:40:39.436 [pimatic-maxcul] debug: ignored auto-ack packet
19:40:39.446 [pimatic-maxcul] debug: incoming raw data from CUL: Z0CA2025003F93A12345600100110
19:40:39.451 [pimatic-maxcul] debug: decoding Message Z0CA2025003F93A12345600100110
19:40:39.460 [pimatic-maxcul] debug: RSSI for Message : -66
19:40:39.486 [pimatic-maxcul] debug: got data from push button 03f93a 1000000000001
19:40:39.523 [pimatic-maxcul] debug: PushButton with deviceId 03f93a updated

19:42:28.932 [pimatic-maxcul] debug: incoming raw data from CUL: Z0BA3000212345603F93A000000
19:42:28.937 [pimatic-maxcul] debug: decoding Message Z0BA3000212345603F93A000000
19:42:28.940 [pimatic-maxcul] debug: RSSI for Message : -74
19:42:28.944 [pimatic-maxcul] debug: ignored auto-ack packet
19:42:28.951 [pimatic-maxcul] debug: incoming raw data from CUL: Z0CA3025003F93A12345600100014
19:42:28.955 [pimatic-maxcul] debug: decoding Message Z0CA3025003F93A12345600100014
19:42:28.958 [pimatic-maxcul] debug: RSSI for Message : -64
19:42:28.963 [pimatic-maxcul] debug: got data from push button 03f93a 1000000000000
19:42:28.970 [pimatic-maxcul] debug: PushButton with deviceId 03f93a updated

**Comment by fbeek** [comment]
THX

**Pull request merged**
