### PR TITLE
Some new features ;)

### PR DESCRIPTION
**Pull request by treban**
HI Florian, 

i have added some new features. 

- **pairing mode** is activated **via"device discovery"** for 30 seconds
  - You do not need to change the plug-in configuration and restart pimatic
  - New paired devices are displayed in the discovery overview. 
- **new devices**
  - WallThermostat 
  - Fake Wall-Thermostat
     -  A reference temperature variable "refTemp" (expression) must be defined in the configuration.
 (expression)
     - refTemp changes are emited to the parId list (the internal heating thermostat sensor is deactivated if a wall-thermostat is paired)
     - The commands are passed to the pairIds list 
  - Fake Shutter-Device
     - The commands are passed to the pairId list
- **pair devices to each other**  
  - all devices can now be connected to each other
  - for this, all devices have now a config send button
  - with the new pairId config property and the config-send button, pairing ist transferred to the device. Pairing must be done reciprocally.
 - **all devices support now groupIDs** 
   - if a group is defined, commands are send to one device but now all devices in the same group are reacting to it
   - The group ID is also sent to the device using the config send button.
- I changed the valve position; i had the problem, that it was above the buttons
 maybe that's not a general problem?
- Overwriting the setContact function for issue #22
- The battery variable for all devices has been changed to string for issue #12

This need some testing. I don't have a shutter or a push button. 
Only wall thermostats and heating thermostats. 

If you want the pull request on another branch, let me know. 

keep in touch
Kosta

### CODE REVIEW

**Comment by fbeek** [comment]
Wow thats great, thank you for your help.

I will check your code and merge it if everything is ok.

**Comment by fbeek** [comment]
I have reviewed your code and on a first view it looks fine, i will merge the code to master branch and test it today and tomorrow. 

I everything wend fine I will release a new version.

Thank you a lot for your help !

**Comment by fbeek** [comment]
It would be nice if you could update the "Usage" Section of the readme with your additions, i will update the Version history etc.

**Comment by treban** [comment]
Yeah nice. I will try to update the usage section these days.

**Pull request merged**
